# Generated by Django 2.2.2 on 2020-02-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOB_TITLE', models.CharField(max_length=30)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Dob', models.DateField()),
                ('Qualification', models.CharField(max_length=30)),
                ('percentage', models.IntegerField()),
                ('Institute', models.CharField(max_length=30)),
                ('Experience', models.IntegerField()),
                ('Contact_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assign_Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('agent_id', models.IntegerField()),
                ('Agent_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CaseCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=30)),
                ('case_details', models.CharField(max_length=30)),
                ('doc', models.DateField()),
                ('evidence', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='case/')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField()),
                ('case_id', models.IntegerField()),
                ('case_name', models.CharField(max_length=30)),
                ('evidence', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='casedetaila/')),
            ],
        ),
        migrations.CreateModel(
            name='CreateAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent_Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Contact_Number', models.IntegerField()),
                ('Qualification', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='agents/')),
            ],
        ),
        migrations.CreateModel(
            name='Defence_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Postings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(default=False, max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('Qualification', models.CharField(max_length=50)),
                ('Percentage', models.IntegerField()),
                ('Experience', models.IntegerField(help_text='In Years')),
                ('Last_date', models.DateField()),
                ('Location', models.CharField(max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='success_stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='success_stories/')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=50)),
                ('Suggession', models.CharField(max_length=100)),
            ],
        ),
    ]
